import path from "path";
import { IMAGES } from "./image";

export const URL = {
    FACEBOOK: "https://www.facebook.com/ecoka.vn/",
    YOUTUBE: "https://www.youtube.com/@JessicaQuangVN",
    MAIL: "mailto:info@ecoka.vn",
    SHOPPING: "https://shopee.vn/quangchanchan",
}

export const total_products: any = [
    {
        id: 1,
        name: "Giỏ Xách Cầm Tay Đẹp Túi Xách Lục Bình Túi Công Sở Túi Xách Cao Cấp Handmade Chaneva Túi Xách Đi Làm Cho Nữ",
        price: "270.000",
        image: IMAGES.PRODUCT_01_MAIN,
        description: "Với mẫu mã đa dạng, họa tiết tinh tế, túi lục bình Chaneva xinh xắn, thời trang và thân thiện với môi trường này đã làm hài lòng rất nhiều khách trong và ngoài nước. Nhìn đơn giản, nhưng để cho ra một sản phẩm túi xách công sở hoàn chỉn và dễ thương thì sản phẩm phải trải qua nhiều công đoạn xử lý và hoàn thiện từ những bàn tay lành nghề của các nghệ nhân Miền Tây.",
        status: "New",
    },
    {
        id: 2,
        name: "Dĩa Lục Bình Size 34cm Dùng Chụp Hình, Trang Trí, Lót Bàn Ăn - Lục Bình Tự Nhiên VN",
        price: "169.000",
        image: IMAGES.PRODUCT_02_MAIN,
        description: "Miếng lót bàn ăn dệt bằng tay từ lục bình thân thiện với môi trường, mang đến cảm giác an toàn hơn, lành mạnh hơn, có ý thức về môi trường. Tạo nên sự đặc biệt bất kỳ ngôi nhà nông thôn nào, phòng ăn boho, phòng khách, nhà nhỏ kiểu nông thôn hoặc kiểu trang trí nội thất theo chủ đề cabin.",
        status: "New",
    },
    {
        id: 3,
        name: "Hàng xuất khẩu, chứng nhận Châu Âu Đế lót ly lục bình | miếng lót ly lục bình tròn handmade 1 miếng",
        price: "32.000",
        image: IMAGES.PRODUCT_03_MAIN,
        description: "Miếng lót ly lục bình được đan bằng tay 100%, mỗi miếng có kích thước là 10 Cm (3,9 inches) phù hợp với hầu hết tất cả các loại ly",
        status: "New",
    },
    {
        id: 4,
        name: "Dây cotton cao cấp - Dây cotton 3mm tự nhiên làm đồ handmade, phụ kiện handmade",
        price: "129.000",
        image: IMAGES.PRODUCT_04_MAIN,
        description: "CHẤT LIỆU COTTON CHẤT LƯỢNG CAO: sợi bông macrame rất mềm mại, bền chắc sẽ dễ dàng làm việc, Sợi bông này được làm từ nguyên liệu tự nhiên và chất lượng cao. Đây sẽ là nguyên liệu tuyệt vời cho tất cả các dự án trang trí hoặc thủ công của bạn.",
        status: "New",
    },
    {
        id: 5,
        name: "Túi Macrame Xách Tay Túi Đựng Laptop Túi Xách Macrame Giỏ Đựng Laptop Handmade Túi Xách Công Sở Cặp Laptop",
        price: "620.000",
        image: IMAGES.PRODUCT_05_MAIN,
        description: "Macrame là nghệ thuật thắt dây cotton sử dụng các nút thắt đơn giản để tạo thành họa tiết trang trí cho các sản phẩm macrame như mành, rèm, túi đeo, xích đu macrame, dây treo cây macrame,… để phục vụ nhu cầu trang trí hoặc công năng hữu ích cho ngôi nhà của bạn theo xu hướng thân thiện với môi trường và tạo điểm nhấn khác biệt cho không gian.",
        status: "New",
    },
    {
        id: 6,
        name: "Giỏ Xách Đẹp Túi Xách Lục Bình Quay Da Thật Túi Công Sở Túi Xách Cao Cấp Chaneva Túi Xách Đi Làm Cho Nữ",
        price: "545.000",
        image: IMAGES.PRODUCT_06_MAIN,
        description: "Với mẫu mã đa dạng, họa tiết tinh tế, túi lục bình Chaneva xinh xắn, thời trang và thân thiện với môi trường này đã làm hài lòng rất nhiều khách trong và ngoài nước. Nhìn đơn giản, nhưng để cho ra một sản phẩm túi xách công sở hoàn chỉnh và dễ thương thì sản phẩm phải trải qua nhiều công đoạn xử lý và hoàn thiện từ những bàn tay lành nghề của các nghệ nhân Miền Tây.",
        status: "New",
    },
    {
        id: 7,
        name: "Giỏ Xách Đẹp Túi Xách Lục Bình Quay Da Thật Túi Công Sở Túi Xách Cao Cấp Handmade Chaneva Túi Xách Đi Làm Cho Nữ",
        price: "490.000",
        image: IMAGES.PRODUCT_07_MAIN,
        description: "Với mẫu mã đa dạng, họa tiết tinh tế, túi lục bình Chaneva xinh xắn, thời trang và thân thiện với môi trường này đã làm hài lòng rất nhiều khách trong và ngoài nước. Nhìn đơn giản, nhưng để cho ra một sản phẩm túi xách công sở hoàn chỉn và dễ thương thì sản phẩm phải trải qua nhiều công đoạn xử lý và hoàn thiện từ những bàn tay lành nghề của các nghệ nhân Miền Tây.",
        status: "New",
    },
    {
        id: 8,
        name: "LÓT LY MÂY - RATTAN",
        price: "10.000",
        image: IMAGES.PRODUCT_08_MAIN,
        description: "Bộ lót ly mây bao gồm 6 miếng lót ly và 1 đế. Đường kính: lót ly: 10cm, đế: 11cm. Chất liệu: guột, mây , song . được đan bằng những bàn tay khéo léo từ nghệ nhân lâu năm và hoàn thiện bằng keo cứng để định hình và giúp sản phẩm bền đẹp hơn.",
        status: "New",
    },
    {
        id: 9,
        name: "Giỏ Xách Đẹp Túi Xách Lục Bình Trang Trí Macrame Hoa Ngang Túi Công Sở Túi Xách Cao Cấp Chaneva Túi Xách Đi Làm Cho Nữ",
        price: "490.000",
        image: IMAGES.PRODUCT_09_MAIN,
        description: "Với mẫu mã đa dạng, họa tiết tinh tế, túi lục bình Chaneva xinh xắn, thời trang và thân thiện với môi trường này đã làm hài lòng rất nhiều khách trong và ngoài nước. Nhìn đơn giản, nhưng để cho ra một sản phẩm túi xách công sở hoàn chỉnh và dễ thương thì sản phẩm phải trải qua nhiều công đoạn xử lý và hoàn thiện từ những bàn tay lành nghề của các nghệ nhân Miền Tây.",
        status: "New",
    },
    {
        id: 10,
        name: "Giỏ Xách Đẹp Túi Xách Lục Bình Trang Trí Macrame Chim Công Túi Công Sở Túi Xách Cao Cấp Chaneva Túi Xách Đi Làm Cho Nữ",
        price: "490.000",
        image: IMAGES.PRODUCT_10_MAIN,
        description: "Với mẫu mã đa dạng, họa tiết tinh tế, túi lục bình Chaneva xinh xắn, thời trang và thân thiện với môi trường này đã làm hài lòng rất nhiều khách trong và ngoài nước. Nhìn đơn giản, nhưng để cho ra một sản phẩm túi xách công sở hoàn chỉnh và dễ thương thì sản phẩm phải trải qua nhiều công đoạn xử lý và hoàn thiện từ những bàn tay lành nghề của các nghệ nhân Miền Tây.",
        status: "New",
    },
    {
        id: 11,
        name: "Giỏ Xách Đẹp Túi Xách Lục Bình Trang Trí Macrame Hoa Dọc Túi Công Sở Túi Xách Cao Cấp Chaneva Túi Xách Đi Làm Cho Nữ",
        price: "490.000",
        image: IMAGES.PRODUCT_11_MAIN,
        description: "Với mẫu mã đa dạng, họa tiết tinh tế, túi lục bình Chaneva xinh xắn, thời trang và thân thiện với môi trường này đã làm hài lòng rất nhiều khách trong và ngoài nước. Nhìn đơn giản, nhưng để cho ra một sản phẩm túi xách công sở hoàn chỉnh và dễ thương thì sản phẩm phải trải qua nhiều công đoạn xử lý và hoàn thiện từ những bàn tay lành nghề của các nghệ nhân Miền Tây.",
        status: "New",
    },
    {
        id: 12,
        name: "Dĩa Lục Bình Size 30cm Dùng Chụp Hình, Trang Trí, Lót Bàn Ăn - Lục Bình Tự Nhiên VN",
        price: "30.000",
        image: IMAGES.PRODUCT_12_MAIN,
        description: "Miếng lót bàn ăn dệt bằng tay từ lục bình thân thiện với môi trường, mang đến cảm giác an toàn hơn, lành mạnh hơn, có ý thức về môi trường. Tạo nên sự đặc biệt bất kỳ ngôi nhà nông thôn nào, phòng ăn boho, phòng khách, nhà nhỏ kiểu nông thôn hoặc kiểu trang trí nội thất theo chủ đề cabin.",
        status: "New",
    },
    {
        id: 13,
        name: "Đế Lót Ly Macrame Cái Hàng Handmade/ Miếng Lót Trang Trí Bàn",
        price: "22.000",
        image: IMAGES.PRODUCT_13_MAIN,
        description: "Được làm hoàn toàn thủ công. Đế lót ly Macrame được làm từ dây cotton thân thiên với môi trường, có thể tái sử dụng. Đế lót được thiết kế để giữ độ ẩm từ nước lạnh, tránh tình trạng đổ nước ra mặt bàn và bảo vệ bề mặt khỏi các thức uống nóng",
        status: "New",
    },
    {
        id: 14,
        name: "Lồng Mèo Handmade từ Lục Bình - Sự Kết Hợp Độc Đáo của Nghệ Thuật và Tính Thực Tiễn",
        price: "249.000",
        image: IMAGES.PRODUCT_14_MAIN,
        description: "Sự kết hợp giữa nghệ thuật và tính thực tiễn, sản phẩm này không chỉ là một món đồ trang trí tuyệt vời mà còn là một phần của cuộc sống hàng ngày của bạn. Bằng cách sử dụng lục bình tự nhiên, các nghệ nhân tài năng đã tạo ra những chiếc vỏ mèo tinh tế, đem lại sự sang trọng và sự tự nhiên cho không gian của bạn.",
        status: "New",
    },
    {
        id: 15,
        name: "Túi Xách Lục Bình Quay Da Thật Trang Trí Macrame Túi Công Sở Túi Xách Cao Cấp Handmade Chaneva Túi Xách Đi Làm Cho Nữ",
        price: "520.000",
        image: IMAGES.PRODUCT_15_MAIN,
        description: "Với mẫu mã đa dạng, họa tiết tinh tế, túi lục bình Chaneva xinh xắn, thời trang và thân thiện với môi trường này đã làm hài lòng rất nhiều khách trong và ngoài nước. Nhìn đơn giản, nhưng để cho ra một sản phẩm túi xách công sở hoàn chỉn và dễ thương thì sản phẩm phải trải qua nhiều công đoạn xử lý và hoàn thiện từ những bàn tay lành nghề của các nghệ nhân Miền Tây.",
        status: "New",
    },
    {
        id: 16,
        name: "Túi Macrame Cầm Tay Túi Macrame Đeo Chéo Màu Trắng Kem Túi Xách Macrame Xách Tay Handmade",
        price: "375.000",
        image: IMAGES.PRODUCT_16_MAIN,
        description: "Macrame là nghệ thuật thắt dây cotton sử dụng các nút thắt đơn giản để tạo thành họa tiết trang trí cho các sản phẩm macrame như mành, rèm, túi đeo, xích đu macrame, dây treo cây macrame,… để phục vụ nhu cầu trang trí hoặc công năng hữu ích cho ngôi nhà của bạn theo xu hướng thân thiện với môi trường và tạo điểm nhấn khác biệt cho không gian.",
        status: "New",
    },
    {
        id: 17,
        name: "Túi Macrame Cầm Tay 3 Mảnh Chaneva Túi Macrame Đeo Vai Túi Xách Macrame Handmade",
        price: "325.000",
        image: IMAGES.PRODUCT_17_MAIN,
        description: "Macrame là nghệ thuật thắt dây cotton sử dụng các nút thắt đơn giản để tạo thành họa tiết trang trí cho các sản phẩm macrame như mành, rèm, túi đeo, xích đu macrame, dây treo cây macrame,… để phục vụ nhu cầu trang trí hoặc công năng hữu ích cho ngôi nhà của bạn theo xu hướng thân thiện với môi trường và tạo điểm nhấn khác biệt cho không gian.",
        status: "New",
    },
    {
        id: 18,
        name: "Hàng xuất khẩu, chứng nhận Châu Âu Thảm Lục Bình Tròn Sofa ,Decor Phòng Khách Phòng Ngủ Vintage",
        price: "215.000",
        image: IMAGES.PRODUCT_18_MAIN,
        description: "Thảm lục bình là một sản phẩm trang trí nội thất. Thảm được đan bằng lục bình sử dụng màu sắc tự nhiên, nhẹ nhàng và sang trọng. Kiểu đan xương cá chắc chắn.",
        status: "New",
    },
    {
        id: 19,
        name: "Giỏ Xách Đẹp Túi Xách Cói Túi Công Sở Túi Xách Cao Cấp Chaneva Túi Xách Đi Làm Cho Nữ Giỏ Xách Thời Trang",
        price: "465.000",
        image: IMAGES.PRODUCT_19_MAIN,
        description: "Với mẫu mã đa dạng, họa tiết tinh tế, túi cói Chaneva xinh xắn, thời trang và thân thiện với môi trường này đã làm hài lòng rất nhiều khách trong và ngoài nước. Nhìn đơn giản, nhưng để cho ra một sản phẩm túi xách công sở hoàn chỉnh và dễ thương thì sản phẩm phải trải qua nhiều công đoạn xử lý và hoàn thiện từ những bàn tay lành nghề của các nghệ nhân Miền Tây",
        status: "New",
    },
    {
        id: 20,
        name: "Túi Đeo Chéo Macrame Chaneva Túi Đựng Điện Thoại Macrame Đeo Vai Túi Xách Macrame Handmade",
        price: "245.000",
        image: IMAGES.PRODUCT_20_MAIN,
        description: "Macrame là nghệ thuật thắt dây cotton sử dụng các nút thắt đơn giản để tạo thành họa tiết trang trí cho các sản phẩm macrame như mành, rèm, túi đeo, xích đu macrame, dây treo cây macrame,… để phục vụ nhu cầu trang trí hoặc công năng hữu ích cho ngôi nhà của bạn theo xu hướng thân thiện với môi trường và tạo điểm nhấn khác biệt cho không gian.",
        status: "New",
    },
    {
        id: 21,
        name: "Túi Xách Lục Bình Quai Họa Tiết Macrame - Nét Đẹp Thân Thiện Và Phong Cách",
        price: "565.000",
        image: IMAGES.PRODUCT_21_MAIN,
        description: "Mang đến sự kết hợp hoàn hảo giữa nét đẹp truyền thống của lục bình, sự mềm mại của macrame và phong cách hiện đại, Túi Xách Lục Bình Họa Tiết Macrame là điểm nhấn độc đáo cho phong cách của bạn.",
        status: "New",
    },
    {
        id: 22,
        name: "Thảm Cói Trải Sàn Thảm Cói Decor Hình Hoa 90cm Ecoka",
        price: "265.000",
        image: IMAGES.PRODUCT_22_MAIN,
        description: "Thảm đan tay phong cách vintage dày dặn, màu sắc tự nhiên,, tiêu chuẩn xuất khẩu, không sử dụng hoá chất, an toàn tuyệt đối ngay cả với trẻ nhỏ.",
        status: "New",
    },
    {
        id: 23,
        name: "Túi Đeo Chéo Macrame Chaneva Túi Đựng Điện Thoại Macrame Đeo Vai Túi Xách Macrame Handmade",
        price: "250.000",
        image: IMAGES.PRODUCT_23_MAIN,
        description: "Kích thước lý tưởng: Dù có kích thước nhỏ gọn, túi vẫn đủ rộng rãi để đựng điện thoại, ví tiền, chìa khóa và một số vật dụng cá nhân khác một cách tiện lợi.",
        status: "New",
    },
    {
        id: 24,
        name: "Túi Macrame Cầm Tay Túi Macrame Đeo Chéo Chaneva Túi Xách Macrame Hình Trống Xách Tay Handmade Giỏ Xách Thời Trang",
        price: "530.000",
        image: IMAGES.PRODUCT_24_MAIN,
        description: "Macrame là nghệ thuật thắt dây cotton sử dụng các nút thắt đơn giản để tạo thành họa tiết trang trí cho các sản phẩm macrame như mành, rèm, túi đeo, xích đu macrame, dây treo cây macrame,… để phục vụ nhu cầu trang trí hoặc công năng hữu ích cho ngôi nhà của bạn theo xu hướng thân thiện với môi trường và tạo điểm nhấn khác biệt cho không gian.",
        status: "New",
    },
    {
        id: 25,
        name: "Set rỗ tre 4 cái",
        price: "199.000",
        image: IMAGES.PRODUCT_25_MAIN,
        description: "Rổ rá, nong, nia, thúng mẹt,… là các vật dụng quen thuộc trong đời sống sinh hoạt của người dân Việt. Chúng thường được làm từ nguyên liệu chính là tre trúc, rất gần gũi, gắn bó với người dân từ nhiều thế kỷ qua",
        status: "New",
    },
];

export const home_products: any = [
    {
        id: 1,
        name: "Giỏ Xách Cầm Tay Đẹp Túi Xách Lục Bình Túi Công Sở Túi Xách Cao Cấp Handmade Chaneva Túi Xách Đi Làm Cho Nữ",
        price: "270.000",
        image: IMAGES.PRODUCT_01_MAIN,
        description: "Với mẫu mã đa dạng, họa tiết tinh tế, túi lục bình Chaneva xinh xắn, thời trang và thân thiện với môi trường này đã làm hài lòng rất nhiều khách trong và ngoài nước. Nhìn đơn giản, nhưng để cho ra một sản phẩm túi xách công sở hoàn chỉn và dễ thương thì sản phẩm phải trải qua nhiều công đoạn xử lý và hoàn thiện từ những bàn tay lành nghề của các nghệ nhân Miền Tây.",
        status: "New",
    },
    {
        id: 2,
        name: "Dĩa Lục Bình Size 34cm Dùng Chụp Hình, Trang Trí, Lót Bàn Ăn - Lục Bình Tự Nhiên VN",
        price: "169.000",
        image: IMAGES.PRODUCT_02_MAIN,
        description: "Miếng lót bàn ăn dệt bằng tay từ lục bình thân thiện với môi trường, mang đến cảm giác an toàn hơn, lành mạnh hơn, có ý thức về môi trường. Tạo nên sự đặc biệt bất kỳ ngôi nhà nông thôn nào, phòng ăn boho, phòng khách, nhà nhỏ kiểu nông thôn hoặc kiểu trang trí nội thất theo chủ đề cabin.",
        status: "New",
    },
    {
        id: 3,
        name: "Hàng xuất khẩu, chứng nhận Châu Âu Đế lót ly lục bình | miếng lót ly lục bình tròn handmade 1 miếng",
        price: "32.000",
        image: IMAGES.PRODUCT_03_MAIN,
        description: "Miếng lót ly lục bình được đan bằng tay 100%, mỗi miếng có kích thước là 10 Cm (3,9 inches) phù hợp với hầu hết tất cả các loại ly",
        status: "New",
    },
    {
        id: 4,
        name: "Dây cotton cao cấp - Dây cotton 3mm tự nhiên làm đồ handmade, phụ kiện handmade",
        price: "129.000",
        image: IMAGES.PRODUCT_04_MAIN,
        description: "CHẤT LIỆU COTTON CHẤT LƯỢNG CAO: sợi bông macrame rất mềm mại, bền chắc sẽ dễ dàng làm việc, Sợi bông này được làm từ nguyên liệu tự nhiên và chất lượng cao. Đây sẽ là nguyên liệu tuyệt vời cho tất cả các dự án trang trí hoặc thủ công của bạn.",
        status: "New",
    },
    {
        id: 5,
        name: "Túi Macrame Xách Tay Túi Đựng Laptop Túi Xách Macrame Giỏ Đựng Laptop Handmade Túi Xách Công Sở Cặp Laptop",
        price: "620.000",
        image: IMAGES.PRODUCT_05_MAIN,
        description: "Macrame là nghệ thuật thắt dây cotton sử dụng các nút thắt đơn giản để tạo thành họa tiết trang trí cho các sản phẩm macrame như mành, rèm, túi đeo, xích đu macrame, dây treo cây macrame,… để phục vụ nhu cầu trang trí hoặc công năng hữu ích cho ngôi nhà của bạn theo xu hướng thân thiện với môi trường và tạo điểm nhấn khác biệt cho không gian.",
        status: "New",
    },
    {
        id: 6,
        name: "Giỏ Xách Đẹp Túi Xách Lục Bình Quay Da Thật Túi Công Sở Túi Xách Cao Cấp Chaneva Túi Xách Đi Làm Cho Nữ",
        price: "545.000",
        image: IMAGES.PRODUCT_06_MAIN,
        description: "Với mẫu mã đa dạng, họa tiết tinh tế, túi lục bình Chaneva xinh xắn, thời trang và thân thiện với môi trường này đã làm hài lòng rất nhiều khách trong và ngoài nước. Nhìn đơn giản, nhưng để cho ra một sản phẩm túi xách công sở hoàn chỉnh và dễ thương thì sản phẩm phải trải qua nhiều công đoạn xử lý và hoàn thiện từ những bàn tay lành nghề của các nghệ nhân Miền Tây.",
        status: "New",
    },
    {
        id: 7,
        name: "Giỏ Xách Đẹp Túi Xách Lục Bình Quay Da Thật Túi Công Sở Túi Xách Cao Cấp Handmade Chaneva Túi Xách Đi Làm Cho Nữ",
        price: "490.000",
        image: IMAGES.PRODUCT_07_MAIN,
        description: "Với mẫu mã đa dạng, họa tiết tinh tế, túi lục bình Chaneva xinh xắn, thời trang và thân thiện với môi trường này đã làm hài lòng rất nhiều khách trong và ngoài nước. Nhìn đơn giản, nhưng để cho ra một sản phẩm túi xách công sở hoàn chỉn và dễ thương thì sản phẩm phải trải qua nhiều công đoạn xử lý và hoàn thiện từ những bàn tay lành nghề của các nghệ nhân Miền Tây.",
        status: "New",
    },
    {
        id: 8,
        name: "LÓT LY MÂY - RATTAN",
        price: "10.000",
        image: IMAGES.PRODUCT_08_MAIN,
        description: "Bộ lót ly mây bao gồm 6 miếng lót ly và 1 đế. Đường kính: lót ly: 10cm, đế: 11cm. Chất liệu: guột, mây , song . được đan bằng những bàn tay khéo léo từ nghệ nhân lâu năm và hoàn thiện bằng keo cứng để định hình và giúp sản phẩm bền đẹp hơn.",
        status: "New",
    },
];

export const related_products: any = [
    {
        id: 1,
        name: "Giỏ Xách Cầm Tay Đẹp Túi Xách Lục Bình Túi Công Sở Túi Xách Cao Cấp Handmade Chaneva Túi Xách Đi Làm Cho Nữ",
        price: "270.000",
        image: IMAGES.PRODUCT_01_MAIN,
        description: "Với mẫu mã đa dạng, họa tiết tinh tế, túi lục bình Chaneva xinh xắn, thời trang và thân thiện với môi trường này đã làm hài lòng rất nhiều khách trong và ngoài nước. Nhìn đơn giản, nhưng để cho ra một sản phẩm túi xách công sở hoàn chỉn và dễ thương thì sản phẩm phải trải qua nhiều công đoạn xử lý và hoàn thiện từ những bàn tay lành nghề của các nghệ nhân Miền Tây.",
        status: "New",
    },
    {
        id: 2,
        name: "Dĩa Lục Bình Size 34cm Dùng Chụp Hình, Trang Trí, Lót Bàn Ăn - Lục Bình Tự Nhiên VN",
        price: "169.000",
        image: IMAGES.PRODUCT_02_MAIN,
        description: "Miếng lót bàn ăn dệt bằng tay từ lục bình thân thiện với môi trường, mang đến cảm giác an toàn hơn, lành mạnh hơn, có ý thức về môi trường. Tạo nên sự đặc biệt bất kỳ ngôi nhà nông thôn nào, phòng ăn boho, phòng khách, nhà nhỏ kiểu nông thôn hoặc kiểu trang trí nội thất theo chủ đề cabin.",
        status: "New",
    },
    {
        id: 3,
        name: "Hàng xuất khẩu, chứng nhận Châu Âu Đế lót ly lục bình | miếng lót ly lục bình tròn handmade 1 miếng",
        price: "32.000",
        image: IMAGES.PRODUCT_03_MAIN,
        description: "Miếng lót ly lục bình được đan bằng tay 100%, mỗi miếng có kích thước là 10 Cm (3,9 inches) phù hợp với hầu hết tất cả các loại ly",
        status: "New",
    },
    {
        id: 4,
        name: "Dây cotton cao cấp - Dây cotton 3mm tự nhiên làm đồ handmade, phụ kiện handmade",
        price: "129.000",
        image: IMAGES.PRODUCT_04_MAIN,
        description: "CHẤT LIỆU COTTON CHẤT LƯỢNG CAO: sợi bông macrame rất mềm mại, bền chắc sẽ dễ dàng làm việc, Sợi bông này được làm từ nguyên liệu tự nhiên và chất lượng cao. Đây sẽ là nguyên liệu tuyệt vời cho tất cả các dự án trang trí hoặc thủ công của bạn.",
        status: "New",
    },
];

export const total_blogs: any = [
    {
        id: 1,
        title: "ECOKA chia sẻ hành trình trao quyền cho thương hiệu Việt trên Amazon tại Đại học FPT",
        thumbnail: IMAGES.BLOG_01_MAIN,
        description: "Chủ tịch HDQT Công ty cổ phần ECOKA, chị Quang Chân Chân, và Tổng Giám Đốc Công ty cổ phần, anh Hà AnhTrường, đã có một buổi chia sẻ đầy ý nghĩa tại trường đại học FPT về hành trình thành công của ECOKA trong việc đưa hàng Việt ra quốc tế trên sàn thương mại điện tử Amazon. Buổi chia sẻ, diễn ra vào ngày 23/6, đã gây được sự quan tâm và ngưỡng mộ từ các sinh viên.",
        date: "09/04/2023 - 20:00",
        author: "Trần My",
        status: "New",
    },
    {
        id: 2,
        title: "Phó Chủ tịch UBND tỉnh Hậu Giang thăm hỏi và động viên các doanh nghiệp",
        thumbnail: IMAGES.BLOG_02_MAIN,
        description: "(NSMT) - Ngày 23/01, ông Trương Cảnh Tuyên - Phó Chủ tịch UBND tỉnh Hậu Giang và ông Nguyễn Vũ Trường - Chủ tịch UBND huyện Long Mỹ cùng lãnh đạo các sở, ban, ngành đã đến thăm và tặng quà cho một số doanh nghiệp trên địa bàn huyện Long Mỹ.",
        date: "09/04/2024 - 20:00",
        author: "Nhịp Sống Miền Tây",
        status: "New",
    },
    {
        id: 3,
        title: "Khởi nghiệp từ cây lục bình, chàng trai kiếm doanh thu hơn 2 tỉ đồng/tháng",
        thumbnail: IMAGES.BLOG_03_MAIN,
        description: "Nhận thấy những vất vả của người dân làng nghề thủ công mỹ nghệ truyền thống, anh Hà Anh Trường (35 tuổi), ngụ tại P.9, TP.Vũng Tàu (tỉnh Bà Rịa - Vũng Tàu) đã đem sản phẩm làm từ cây lục bình đi xuất ngoại với doanh thu hơn 2 tỉ đồng/tháng.",
        date: "23/01/2024 - 15:57",
        author: "Báo Thanh Niên",
        status: "New",
    },
];

export const home_blogs: any = [
    {
        id: 1,
        title: "ECOKA chia sẻ hành trình trao quyền cho thương hiệu Việt trên Amazon tại Đại học FPT",
        thumbnail: IMAGES.BLOG_01_MAIN,
        description: "Chủ tịch HDQT Công ty cổ phần ECOKA, chị Quang Chân Chân, và Tổng Giám Đốc Công ty cổ phần, anh Hà AnhTrường, đã có một buổi chia sẻ đầy ý nghĩa tại trường đại học FPT về hành trình thành công của ECOKA trong việc đưa hàng Việt ra quốc tế trên sàn thương mại điện tử Amazon. Buổi chia sẻ, diễn ra vào ngày 23/6, đã gây được sự quan tâm và ngưỡng mộ từ các sinh viên.",
        date: "09/04/2023 - 20:00",
        author: "Trần My",
        status: "New",
    },
    {
        id: 2,
        title: "Phó Chủ tịch UBND tỉnh Hậu Giang thăm hỏi và động viên các doanh nghiệp",
        thumbnail: IMAGES.BLOG_02_MAIN,
        description: "(NSMT) - Ngày 23/01, ông Trương Cảnh Tuyên - Phó Chủ tịch UBND tỉnh Hậu Giang và ông Nguyễn Vũ Trường - Chủ tịch UBND huyện Long Mỹ cùng lãnh đạo các sở, ban, ngành đã đến thăm và tặng quà cho một số doanh nghiệp trên địa bàn huyện Long Mỹ.",
        date: "09/04/2024 - 20:00",
        author: "Nhịp Sống Miền Tây",
        status: "New",
    },
    {
        id: 3,
        title: "Khởi nghiệp từ cây lục bình, chàng trai kiếm doanh thu hơn 2 tỉ đồng/tháng",
        thumbnail: IMAGES.BLOG_03_MAIN,
        description: "Nhận thấy những vất vả của người dân làng nghề thủ công mỹ nghệ truyền thống, anh Hà Anh Trường (35 tuổi), ngụ tại P.9, TP.Vũng Tàu (tỉnh Bà Rịa - Vũng Tàu) đã đem sản phẩm làm từ cây lục bình đi xuất ngoại với doanh thu hơn 2 tỉ đồng/tháng.",
        date: "23/01/2024 - 15:57",
        author: "Báo Thanh Niên",
        status: "New",
    },
];

export const categories: any = [
    {
        id: 1,
        name: 'Thời Trang',
        path: '/thoi-trang'
    },
    {
        id: 2,
        name: 'Nhà Bếp',
        path: '/nha-bep',
    },
    {
        id: 3,
        name: 'Trang Trí Nhà Cửa',
        path: '/trang-tri-nha-cua',
    },
    {
        id: 4,
        name: 'Nội Thất',
        path: '/noi-that',
    },
]