export const IMAGES = {
    LOGO: "/logo.png",
    LOGO_CIRCLE: "/logo-circle.png",
    VIDEO_HOME: "/home.mp4",
    VIDEO_ABOUT: "/about.mp4",
    HOME_GRID: "/home-grid.png",
    BANNER_LOGO: "/banner-logo.png",
    BREADCRUMB: "/breadcrumb.png",
    FLAG_VN: "/flag-vietnam.png",
    //
    BLOG_01_MAIN: "/ecoka-blog-01-main.jpg",
    BLOG_02_MAIN: "/ecoka-blog-02-main.jpg",
    BLOG_03_MAIN: "/ecoka-blog-03-main.webp",
    //
    PRODUCT_01_MAIN: "/ecoka-product-01-main.jpg",
    PRODUCT_02_MAIN: "/ecoka-product-02-main.jpg",
    PRODUCT_03_MAIN: "/ecoka-product-03-main.jpg",
    PRODUCT_04_MAIN: "/ecoka-product-04-main.webp",
    PRODUCT_05_MAIN: "/ecoka-product-05-main.webp",
    PRODUCT_06_MAIN: "/ecoka-product-06-main.webp",
    PRODUCT_07_MAIN: "/ecoka-product-07-main.webp",
    PRODUCT_08_MAIN: "/ecoka-product-08-main.webp",
    PRODUCT_09_MAIN: "/ecoka-product-09-main.webp",
    PRODUCT_10_MAIN: "/ecoka-product-10-main.webp",
    PRODUCT_11_MAIN: "/ecoka-product-11-main.webp",
    PRODUCT_12_MAIN: "/ecoka-product-12-main.webp",
    PRODUCT_13_MAIN: "/ecoka-product-13-main.webp",
    PRODUCT_14_MAIN: "/ecoka-product-14-main.webp",
    PRODUCT_15_MAIN: "/ecoka-product-15-main.webp",
    PRODUCT_16_MAIN: "/ecoka-product-16-main.webp",
    PRODUCT_17_MAIN: "/ecoka-product-17-main.webp",
    PRODUCT_18_MAIN: "/ecoka-product-18-main.webp",
    PRODUCT_19_MAIN: "/ecoka-product-19-main.webp",
    PRODUCT_20_MAIN: "/ecoka-product-20-main.webp",
    PRODUCT_21_MAIN: "/ecoka-product-21-main.webp",
    PRODUCT_22_MAIN: "/ecoka-product-22-main.webp",
    PRODUCT_23_MAIN: "/ecoka-product-23-main.webp",
    PRODUCT_24_MAIN: "/ecoka-product-24-main.webp",
    PRODUCT_25_MAIN: "/ecoka-product-25-main.webp",
    //
    ESG_ENV: "/ecoka-esg-env.jpg",
    ESG_SOCIAL: "/ecoka-esg-social.jpg",
    ESG_MANAGE: "/ecoka-esg-manage.jpg",
}